### ISSUE TITLE
How to get the file "saved_meshes/robot_state_kinematic_val.json"

### ISSUE THREAD

**Issue by p1ckpep** [BoyuanChen/visual-selfmodeling#3]
Hello, I am learning your significant repo, I succeeded to train your visual self-model and get the _robot_state.json_, but I have a problem when I run your command in "Training" part of "To use our pre-trained self-model to train a small network to predict end-effector position", it seems that there's no file named "_robot_state_kinematic_val.json_",  and I'm new to learn Deep Learing, so could you help me how to generate that file?
logs:
(env-visual-selmodeling) $ CUDA_VISIBLE_DEVICES=0 python ../main.py ../configs/state_condition_kinematic/config1.yaml kinematic ./logs_state-condition_new-global-siren-sdf_1/lightning_logs/version_0/checkpoints/
{'coord_system': 'cartesian',
 'data_filepath': '../saved_meshes',
 'dof': 4,
 'epochs': 1000,
 'gamma': 0.5,
 'if_cuda': True,
 'log_dir': 'logs',
 'loss_type': 'siren_sdf_kinematic',
 'lr': 0.0009,
 'lr_schedule': [10000000],
 'model_name': 'state-condition-kinematic',
 'num_gpus': 1,
 'num_workers': 8,
 'seed': 1,
 'tag': 'new-global-siren-sdf',
 'task_batch': 9600,
 'test_batch': 4500,
 'train_batch': 4500,
 'val_batch': 4500}
Global seed set to 1
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
Traceback (most recent call last):
  File "../main.py", line 173, in <module>
    main_kinematic()
  File "../main.py", line 118, in main_kinematic
    trainer.fit(model)
  File "/data/lwh22/anaconda3/envs/env-visual-selmodeling/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self.call_setup_hook(model)
  File "/data/lwh22/anaconda3/envs/env-visual-selmodeling/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1066, in call_setup_hook
    model.setup(stage_name)
  File "/data/lwh22/hust_pj/visual-selfmodeling/models.py", line 204, in setup
    pointcloud_folder=self.hparams.data_filepath)
  File "/data/lwh22/hust_pj/visual-selfmodeling/dataset.py", line 97, in __init__
    self.robot_state_dict = self.load_robot_state()
  File "/data/lwh22/hust_pj/visual-selfmodeling/dataset.py", line 134, in load_robot_state
    with open(robot_state_filepath, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../saved_meshes/robot_state_kinematic_val.json'

**Comment by iamlilAJ** [comment]
Hi, I encountered similar issues. 

It can be resolved by modifying the directory in the **config1.yaml**.

**Comment by MoeHH** [comment]
Hello there, 

I am facing an issue with executing  the following command "CUDA_VISIBLE_DEVICES=0 python ../main.py ../configs/state_condition_kinematic/config1.yaml kinematic ./logs_state-condition_new-global-siren-sdf_1/lightning_logs/version_0/checkpoints/;" as it required robot_state_kinematic_val.json as the following error "FileNotFoundError: [Errno 2] No such file or directory: '../saved_meshes/robot_state_kinematic_val.json'". 

The robot_state_kinematic_val.json file is not generated or saved at the Saved_meshes folder. Please can you advise?

Thanks

**Comment by iamlilAJ** [comment]
Hi, I am not sure but  you may need to run the first command to generate "cd scripts;
CUDA_VISIBLE_DEVICES=0 python ../main.py ../configs/state_condition/config1.yaml NA;"
